apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: pi05-ft-single-node-fzy-test  # 任务名称
  namespace: bonete05        # 你的 Namespace
spec:
  queue: bonete05
  minAvailable: 1            # 单节点运行，设为 1
  plugins:
    ssh: []
    svc: []
    env: []
  tasks:
    - name: server
      replicas: 1            # 单节点运行，设为 1
      template:
        spec:
          schedulerName: volcano
          restartPolicy: Never
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 100Gi
            - name: data
              persistentVolumeClaim:
                claimName: pvc-vast-bonete05  # 挂载你的 VAST 存储
          containers:
            - name: server
              image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04 # 使用你的 AMLT 镜像
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: data
                  mountPath: /data           # 在 K8s 中，你的持久化数据都在 /data 下
              command: ["/bin/bash","-lc"]
              args:
                - |
                  # 1. 进入工作目录 (假设你的代码已经通过某种方式在 /data/openpi)
                  # 注意：K8s 不像 AMLT 会自动上传 local_dir，你需要先确保代码在 PVC 存储里
                  cd /data/openpi 

                  # 2. 安装系统依赖 (从 AMLT 迁移)
                  sudo apt-get update
                  sudo apt-get install -y libglib2.0-0 libgl1 libsm6 libxext6 libxrender1 vim curl

                  # 3. 安装工具 (从 AMLT 迁移)
                  pip install nvitop
                  
                  # 4. 执行你的环境设置脚本
                  bash setup_env.sh
                  # 注意：K8s 容器内 source 环境变量可能需要指向具体路径
                  [ -f ~/.local/bin/env ] && source ~/.local/bin/env

                  # 5. 准备目录与链接 (从 AMLT 迁移)
                  mkdir -p ./data
                  mkdir -p ./checkpoints
                  # 这里的路径需要根据你 VAST 存储的真实结构调整
                  ln -s /data/agibot_beta_split_500_resize_224/* ./data/ 2>/dev/null || true

                  # 6. 运行训练脚本
                  export WANDB_API_KEY=994cd7b5e79dffcab948d9a69766810153a12b48
                  export WANDB_ENTITY=aaronfeng24
                  export EXP_NAME_ENV="pi05_ft_agibot_static_1212_HSDP_formal"
                  
                  echo "Starting Training..."
                  bash ./scripts/train_jax.sh 512

                  # 保持容器运行，方便排错
                  sleep infinity
              resources:
                requests:
                  nvidia.com/gpu: "8"        # 请求 8 张 B200
                  cpu: "192"
                  memory: "2000Gi"
                limits:
                  nvidia.com/gpu: "8"
                  cpu: "192"
                  memory: "2000Gi"