description: I'm writing to request the 8xA100 to process the data.

target:
  service: singularity
  name: msrresrchvc
  workspace_name: azmlws2igshare

environment:
  image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04
  

storage:
  my_storage:
    storage_account_name: igshare
    container_name: v-zhifeng
    mount_dir: /scratch/v-zhifeng
  
code:
  local_dir: /home/v-zhifeng/HPE/openpi/
  ignore:
    - agibotworld
    - .venv/
    - data/
    - checkpoints/
    - old_scripts/
    
jobs:
- name: pi05_ft_static_bs512_80G4A100_2nodes
  sku: 2x80G4-A100
  priority: high
  preemptible: False
  identity: managed
  process_count_per_node: 1
  command:
  - sudo apt-get update
  - sudo apt-get install -y libglib2.0-0 libgl1 libsm6 libxext6 libxrender1
  - cd /scratch/amlt_code/
  - curl -L "https://aka.ms/downloadazcopy-v10-linux" -o azcopy_v10.tar.gz
  - tar -xzf azcopy_v10.tar.gz
  - cd azcopy_linux_amd64_*
  - sudo mv azcopy /scratch/amlt_code/
  - cd /scratch/amlt_code/
  - pip install nvitop
  - sudo apt-get update && sudo apt-get install -y vim
  - bash setup_env.sh
  - source ~/.local/bin/env
  - mkdir -p /scratch/amlt_code/data
  - mkdir -p /scratch/amlt_code/checkpoints
  - ln -s /scratch/v-zhifeng/agibot_beta_split_500_resize_224/* /scratch/amlt_code/data/
  - ln -s /scratch/v-zhifeng/openpi/checkpoints/* /scratch/amlt_code/checkpoints/
  - >
    cd /scratch/amlt_code &&
    export WANDB_API_KEY=994cd7b5e79dffcab948d9a69766810153a12b48 &&
    export WANDB_ENTITY=aaronfeng24 &&
    bash ./scripts/train_jax_multinodes.sh 512
  - sleep infinity